server:
  port: 9090

spring:
  application:
    name: gateway-service22

  cloud:
    gateway:
      routes:

        - id: driver-service
          uri: lb://DRIVER-SERVICE22
          predicates:
            - Path=/api/drivers/**

        - id: ride-service
          uri: lb://RIDE-SERVICE22
          predicates:
            - Path=/api/rides/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
