spring:
  application:
    name: ride-service22

  datasource:
    url: jdbc:mysql://localhost:3306/ride_db?createDatabaseIfNotExist=true
    username: root
    password: Adi@2552
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
server:
  port: 8082



management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: "*"
# management:
#   tracing:
#     sampling:
#       probability: 1.0

#   endpoints:
#     web:
#       exposure:
#         include: "*"
